#if UNIGINE_DOUBLE
using Scalar = System.Double;
using Vec2 = Unigine.dvec2;
using Vec3 = Unigine.dvec3;
using Vec4 = Unigine.dvec4;
using Mat4 = Unigine.dmat4;
#else
using Scalar = System.Single;
using Vec2 = Unigine.vec2;
using Vec3 = Unigine.vec3;
using Vec4 = Unigine.vec4;
using Mat4 = Unigine.mat4;
#endif

using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using Unigine;
using static Blend2D;

[Component(PropertyGuid = "AUTOGENERATED_GUID")]
public class BasicAnimation : Component
{
    public ObjectMeshSkinned meshSkinned = null;
    public enum AnimationProcessTypes
    {
        EveryFrame = 0,
        CustomRate = 1
    }
    public enum AnimationEndTypes
    {
        Loop = 0,
        Hold = 1,
        PingPong = 2
    }
    public class NamedAnimation
    {
        public string name;

        [Parameter(Group = "Animation Properties")]
        [ParameterAsset(Filter = "anim")]
        public AssetLink asset;
        [ShowInEditor]
        [Parameter(Group = "Animation Properties")]
        public float framesPerSecond = 30.0f;
        [ShowInEditor]
        [Parameter(Group = "Animation Properties")]
        public AnimationEndTypes endType;
        [ShowInEditor]
        [Parameter(Group = "Animation Properties")]
        public int frameNumber = -1;
        [ShowInEditor]
        [Parameter(Group = "Animation Properties")]
        public int from = -1;
        [ShowInEditor]
        [Parameter(Group = "Animation Properties")]
        public int to = -1;
    }

    public class AnimationTrigger
    {
        public string name;
        public string animation;
        public float frame;
        public EventInvoker callback = new EventInvoker();
        public float currentFrame = -1;
    };

    public class BoneInterpolatedRotation
    {
        public int boneIndex;
        public string boneName;
        public quat targetRotation;
        public quat startRotation;
        public quat currentRotation;
        public float blendAmount;
        public float blendTarget;
        public float degreesPerSecond;
        public float angularDistance;
    }

    public class BoneRotation
    {
        public int boneIndex;
        public string boneName;
        public quat rotation;
        public float blendOutDegreesPerSecond = 0.0f;
        public float blendOutAmount = 0.0f;
    }

    [ShowInEditor]
    private List<NamedAnimation> animations = new List<NamedAnimation>();

    [ShowInEditor]
    [Parameter(Tooltip = "Animation update type")]
    private AnimationProcessTypes processType = new AnimationProcessTypes();

    [ShowInEditor]
    [Parameter(Tooltip = "Animation update rate(FPS)")]
    [ParameterCondition(nameof(processType), (int)AnimationProcessTypes.CustomRate)]
    private int processRate = 30;

    private float timeScale = 1.0f;
    private float updateTime = 0.0f;
    private float lastUpdateTime = 0.0f;
    private float updateTimeDelta = 0.0f;

    //names
    private string animationName = null;
    private string previousAnimationName = null;

    //layers
    private int layerNum = 0;
    private int prevLayerNum = 0;

    //blends
    private float prevCurBlendAmount = 1.0f;
    private float blendAmount = 0;
    private float blendTarget = 0;

    //blend speed
    private float blendSpeedFactor = 3.75f;

    //playback rate
    private float animationFPS = 30.0f;

    //animation type
    private bool pingPongForward = true;

    private List<AnimationTrigger> animationTriggers = new List<AnimationTrigger>();

    private List<BoneInterpolatedRotation> boneInterpolatedRotations = new List<BoneInterpolatedRotation>();
    private List<BoneRotation> boneRotations = new List<BoneRotation>();

    public EventInvoker<BasicAnimation> preAnimtationUpdate = new EventInvoker<BasicAnimation>();
    public EventInvoker<BasicAnimation> postAnimationUpdate = new EventInvoker<BasicAnimation>();

    public EventInvoker<string> onBlendedOut = new EventInvoker<string>();
    public EventInvoker<string> onBlendedIn = new EventInvoker<string>();
    public EventInvoker<string, string> onAnimationChangeComplete = new EventInvoker<string, string>();

    public EventInvoker<string> onBoneInterpolateDone = new EventInvoker<string>();
    public EventInvoker<string> onClearBoneInterpolateDone = new EventInvoker<string>();
    public EventInvoker<string> onClearBoneRotationSmoothDone = new EventInvoker<string>();

    void Init()
    {
        meshSkinned = node as ObjectMeshSkinned;
        if (!meshSkinned)
            return;
        InitAnimations();
        
        if (processType == AnimationProcessTypes.CustomRate)
        {
            if (processRate > 0)
            {
                updateTime = (float)(1.0f / processRate);
                lastUpdateTime = updateTime;//force initial animation update
            }
            else
            {
                Log.Warning($"Blend tree fps must be greater than 0");
                processType = AnimationProcessTypes.EveryFrame;
            }
        }
    }

    private void UpdateSyncThread()
    {
        if (!meshSkinned)
            return;

        if (timeScale < MathLib.EPSILON)
            return;

        if (processType == AnimationProcessTypes.CustomRate)
        {
            lastUpdateTime += Game.IFps;
            if (lastUpdateTime > updateTime)
            {
                updateTimeDelta = lastUpdateTime;
                lastUpdateTime = 0.0f;
            }
            else
            {
                return;
            }
        }
        else
        {
            updateTimeDelta = Game.IFps;
        }

        preAnimtationUpdate.Run(this);

        if (animationName != null)
            UpdateAnimations();

        if (boneInterpolatedRotations.Count > 0 || boneRotations.Count > 0)
            UpdateBoneTransforms();

        postAnimationUpdate.Run(this);
    }

    #region animations
    private void InitAnimations()
    {
        meshSkinned.AddLayer();
        layerNum = meshSkinned.NumLayers - 1;
        meshSkinned.AddLayer();
        prevLayerNum = meshSkinned.NumLayers - 1;
    }

    private void UpdateAnimations()
    {
        if (animationName != null)
        {
            bool blending = !(blendTarget == 1.0 && blendAmount == 1.0);
            bool prevCurBlending = !(prevCurBlendAmount == 1.0);
            AdvanceFrame();
            if (prevCurBlending)
            {
                UpdatePrevCurBlend();
                if (prevCurBlendAmount < 1.0f)
                    ApplyPrevCur();
                else
                {
                    meshSkinned.ClearLayer(prevLayerNum);
                    onAnimationChangeComplete.Run(animationName, previousAnimationName);
                }
            }

            if (blending)
            {
                UpdateBlend();
            }
            Apply();

            //check animation triggers
            if (animationTriggers.Count > 0)
            {
                NamedAnimation animation = GetNamedAnimation(animationName);
                if (animation.frameNumber != -1)
                {
                    return;
                }
                foreach (AnimationTrigger animationTrigger in animationTriggers)
                {
                    if (animationTrigger.animation == animationName)
                    {
                        int totalFrames = GetTotalFrames(animation);
                        CheckTrigger(animationTrigger, layerNum, totalFrames, !pingPongForward);
                    }
                }
            }
        }
    }

    private float ComputeFrame(NamedAnimation animation)
    {
        float delta = updateTimeDelta * animationFPS * timeScale;
        if (animation.endType == AnimationEndTypes.Loop)
            return meshSkinned.GetLayerFrame(layerNum) + delta;
        else if (animation.endType == AnimationEndTypes.Hold)
        {
            float nextFrame = meshSkinned.GetLayerFrame(layerNum) + delta;
            int totalFrames = GetTotalFrames(animation);
            if (nextFrame >= totalFrames)
                return totalFrames;
            else
                return nextFrame;
        }
        else//Ping pong
        {
            int totalFrames = GetTotalFrames(animation);
            if (pingPongForward)
            {
                float nextFrame = meshSkinned.GetLayerFrame(layerNum) + delta;
                if (nextFrame >= totalFrames)
                {
                    //ping pong animation type has crossed over the length of the animation
                    if (nextFrame < meshSkinned.GetLayerFrame(layerNum) + totalFrames)
                    {
                        //crossover length is less than the length of the animation
                        //reverse direction starting from the end of the animation
                        pingPongForward = false;
                        return totalFrames - (nextFrame - totalFrames);
                    }
                    else
                    {
                        //crossover length is greater than the length of the animation cycle
                        //this is unlikely but possible depending on the relative animation length and configured updateTimeDelta
                        //see how many animation cycles should have occurred since the last frame
                        //this indicates how many additional "bounces" occurred after crossing the animation length
                        //an odd number of additional bounces means new frame starts at the beginning by an amount (nextframe - currentframe) % animationLength
                        //an even number of additional bounces means reverse direction starting at the end by an amount (nextframe - currentframe) % animationLength
                        float cycles = (nextFrame - meshSkinned.GetLayerFrame(layerNum)) / totalFrames;
                        int bounces = (int)MathLib.Round(cycles, MidpointRounding.ToZero);
                        if (bounces % 2 != 0)
                        {
                            //odd number of additional bounces
                            return (nextFrame - meshSkinned.GetLayerFrame(layerNum)) % totalFrames;
                        }
                        else
                        {
                            //even number of additional bounces
                            pingPongForward = false;
                            return totalFrames - ((nextFrame - meshSkinned.GetLayerFrame(layerNum)) % totalFrames);
                        }
                    }
                }
                else
                    return nextFrame;
            }
            else
            {
                float nextFrame = meshSkinned.GetLayerFrame(layerNum) - delta;
                if (nextFrame <= 0)
                {
                    //reversing the ping pong animation has crossed over the zero frame of the animation
                    if (nextFrame > meshSkinned.GetLayerFrame(layerNum) - totalFrames)
                    {
                        //crossover length is less than the length of the animation (nextFrame is negative)
                        //reverse direction to forward, make nextFrame positive, and start at the beginning by amount nextFrame
                        pingPongForward = true;
                        return MathLib.Negative(nextFrame);
                    }
                    else
                    {
                        //crossover length is greater than the length of the animation cycle
                        //this is unlikely but possible depending on the relative animation length and configured updateTimeDelta
                        //see how many animation cycles should have occurred since the last frame
                        //this indicates how many additional "bounces" occurred after crossing the animation length
                        //an odd number of additional bounces means new frame starts at the end by an amount (nextframe - currentframe) % animationLength
                        //an even number of additional bounces means reverse direction starting from the end by an amount (nextframe - currentframe) % animationLength
                        float cycles = (nextFrame - meshSkinned.GetLayerFrame(layerNum)) / totalFrames;
                        int bounces = (int)MathLib.Round(MathLib.Negative(cycles), MidpointRounding.ToZero);
                        if (bounces % 2 != 0)
                        {
                            //odd number of additional bounces
                            return totalFrames - (MathLib.Negative(nextFrame - meshSkinned.GetLayerFrame(layerNum)) % totalFrames);
                        }
                        else
                        {
                            //even number of additional bounces
                            pingPongForward = true;
                            return MathLib.Negative(nextFrame - meshSkinned.GetLayerFrame(layerNum)) % totalFrames;
                        }

                    }
                }
                else
                    return nextFrame;
            }
        }
    }

    private int GetTotalFrames(NamedAnimation animation)
    {
        if (animation.from == -1 && animation.to == -1)
            return meshSkinned.GetLayerNumFrames(layerNum);
        int startFrame = animation.from == -1 ? 0 : animation.from;
        int endFrame = animation.to == -1 ? meshSkinned.GetLayerNumFrames(layerNum) : animation.to - 1;
        return endFrame - startFrame;
    }

    private void AdvanceFrame()
    {
        if (animationName != null)
        {
            NamedAnimation animation = GetNamedAnimation(animationName);
            if (animation.frameNumber == -1)
            {
                float frame = ComputeFrame(animation);
                meshSkinned.SetLayerFrame(layerNum, frame, animation.from, animation.to);
            }
            else
            {
                meshSkinned.SetLayerFrame(layerNum, animation.frameNumber);
            }
        }
    }

    private void UpdateBlend()
    {
        float lerpAmount = blendSpeedFactor * updateTimeDelta * timeScale; //globalLerpAmount;

        if (blendTarget > blendAmount)
        {
            blendAmount = (float)Unigine.MathLib.Min(blendAmount + lerpAmount, 1.0f);
            if (blendAmount == 1.0f)
            {
                onBlendedIn.Run(animationName);
            }
        }

        else if (blendTarget < blendAmount)
        {
            blendAmount = (float)Unigine.MathLib.Max(blendAmount - lerpAmount, 0.0f);
            if (blendAmount == 0.0f)
            {
                if (animationName != null)
                {
                    ResetTriggersForAnimation(animationName);

                    meshSkinned.SetLayerFrame(layerNum, 0.0f);
                    animationName = null;
                    onBlendedOut.Run(animationName);
                }
            }
        }
    }

    private void UpdatePrevCurBlend()
    {
        float lerpAmount = blendSpeedFactor * updateTimeDelta * timeScale; //globalLerpAmount;
        blendAmount = (float)Unigine.MathLib.Min(blendAmount + lerpAmount, 1.0f);
    }

    private void ApplyPrevCur()
    {
        meshSkinned.LerpLayer(layerNum, prevLayerNum, layerNum, prevCurBlendAmount);
    }

    private void Apply()
    {
        meshSkinned.LerpLayer(0, 0, layerNum, blendAmount);
    }

    private void ResetTriggersForAnimation(string animationTriggerName)
    {
        if (animationTriggers.Count == 0)
            return;
        AnimationTrigger result = animationTriggers.Find(animationTrigger => animationTrigger.name == animationTriggerName);
        if (result != null)
            result.currentFrame = -1.0f;
    }

    public void AddAnimationTrigger(string triggerName, string animationName, float time, EventDelegate cb)
    {
        AnimationTrigger result = animationTriggers.Find(animationTrigger => animationTrigger.name == triggerName);
        if (result == null)
        {
            AnimationTrigger animationTrigger = new AnimationTrigger() { name = triggerName, animation = animationName, frame = time, currentFrame = -1.0f };
            animationTrigger.callback.Connect(cb);
            animationTriggers.Add(animationTrigger);
            return;
        }
        Log.Warning($"AddAnimationTrigger: trigger name {triggerName} is already taken");
    }

    public void RemoveAnimationTrigger(string triggerName, EventDelegate cb)
    {
        AnimationTrigger result = animationTriggers.Find(animationTrigger => animationTrigger.name == triggerName);
        if (result != null)
        {
            if (!result.callback.Disconnect(cb))
            {
                Log.Warning($"RemoveAnimationTrigger: EventDelegate Disconnect was unsuccessful while removing {triggerName}");
            }
            animationTriggers.Remove(result);
        }
    }

    public void SuspendAnimationTrigger(string triggerName)
    {
        AnimationTrigger result = animationTriggers.Find(animationTrigger => animationTrigger.name == triggerName);
        if (result != null)
        {
            result.callback.Enabled = false;
            return;
        }
        Log.Warning($"SuspendAnimationTrigger: trigger name {triggerName} not found");
    }

    public void ResumeAnimationTrigger(string triggerName)
    {
        AnimationTrigger result = animationTriggers.Find(animationTrigger => animationTrigger.name == triggerName);
        if (result != null)
        {
            result.callback.Enabled = true;
            return;
        }
        Log.Warning($"ResumeAnimationTrigger: trigger name {triggerName} not found");
    }

    public void SetAnimation(string newAnimationName, float speedFactor = 3.75f)
    {
        //aleways reset triggers regardless of whether we're switching animations or not
        if (animationName != null && (animationTriggers.Count > 0))
        {
            ResetTriggersForAnimation(animationName);
        }

        if (newAnimationName == animationName)
        {
            //resetting the same animation
            //copy bone states to prev layer, reset prevCur blend and reset current frame
            meshSkinned.CopyLayer(prevLayerNum, 0);
            prevCurBlendAmount = 0.0f;
            NamedAnimation animation = GetNamedAnimation(newAnimationName);
            if (animation.frameNumber == -1)
                meshSkinned.SetLayerFrame(layerNum, 0);
            blendSpeedFactor = speedFactor;
            return;
        }
        foreach (NamedAnimation animation in animations)
        {
            if (animation.name == newAnimationName)
            {
                if (animationName != null)
                {
                    //switching animations
                    //initialize prevCur blend value and swap current and prev layer numbers
                    var tempLayerNum = prevLayerNum;
                    prevLayerNum = layerNum;
                    layerNum = tempLayerNum;
                    previousAnimationName = animationName;
                    prevCurBlendAmount = 0.0f;
                    animationFPS = animation.framesPerSecond;
                }
                else
                {
                    //setting a new animation
                    //copy current bone states to prev layer, reset prevCur blend and reset current frame
                    blendAmount = 0.0f;
                    blendTarget = 1.0f;
                    meshSkinned.CopyLayer(prevLayerNum, 0);
                    prevCurBlendAmount = 0.0f;
                    animationFPS = animation.framesPerSecond;
                }

                //requested animation found
                //load new animation into layer, reset frame
                animationName = newAnimationName;
                meshSkinned.SetLayerAnimationFilePath(layerNum, animation.asset.Path);
                meshSkinned.SetLayerFrame(layerNum, 0);
                blendSpeedFactor = speedFactor;
                return;
            }
        }
        Log.Warning($"\nSetAnimation(): {animationName} not found");
    }

    public void SetFrame(float frame)
    {
        if (animationName != null)
        {
            meshSkinned.SetLayerFrame(layerNum, MathLib.Max(frame, meshSkinned.GetLayerNumFrames(layerNum)));
        }

    }

    public string GetAnimation()
    {
        return animationName;
    }

    public string GetEndType()
    {
        if (animationName != null)
        {
            NamedAnimation animation = GetNamedAnimation(animationName);
            return animation.endType.ToString();
        }
        else
        {
            Log.Warning($"\nGetEndType(): no animation set");
            return null;
        }
    }

    public string GetAnimationEndType(string animationToCheck)
    {
        NamedAnimation animation = GetNamedAnimation(animationToCheck);
        return animation.endType.ToString();
    }

    public void SetAnimationEndType(string animationName, AnimationEndTypes endType)
    {
        NamedAnimation fbAnimation = GetNamedAnimation(animationName);
        fbAnimation.endType = endType;
    }

    public void SetAnimationFPS(float fps)
    {
        animationFPS = fps;
    }

    public float GetAnimationFPS()
    {
        return animationFPS;
    }

    public void ClearAnimation()
    {
        blendTarget = 0.0f;
    }
    #endregion

    #region bone transforms

    private void UpdateBoneTransforms()
    {

        float delta = updateTimeDelta * timeScale;
        for (int i = boneInterpolatedRotations.Count - 1; i >= 0; i--)
        {
            BoneInterpolatedRotation boneInterpolatedRotation = boneInterpolatedRotations[i];
            if (boneInterpolatedRotation.blendAmount == 1.0f && boneInterpolatedRotation.blendTarget == 1.0f)
            {
                ApplyBoneRotation(boneInterpolatedRotation.boneIndex, boneInterpolatedRotation.currentRotation);
                continue;
            }
            else
            {
                //Log.Warning($"\nblendamount: {boneInterpolatedRotation.blendAmount}\n");
                if (boneInterpolatedRotation.blendAmount < 1.0f && boneInterpolatedRotation.blendTarget == 1.0f)
                {
                    //updating interpolate blend
                    //blending from currentRotation to targetRotation
                    float deltaBlend = (boneInterpolatedRotation.degreesPerSecond * delta) / boneInterpolatedRotation.angularDistance;
                    boneInterpolatedRotation.blendAmount = (float)Unigine.MathLib.Min(boneInterpolatedRotation.blendAmount + deltaBlend, 1.0f);
                    ApplyBoneInterpolatedRotation(boneInterpolatedRotation);
                    if (boneInterpolatedRotation.blendAmount == 1.0f)
                    {
                        onBoneInterpolateDone.Run(boneInterpolatedRotation.boneName);
                    }
                }
                else if (boneInterpolatedRotation.blendAmount > 0.0f && boneInterpolatedRotation.blendTarget == 0.0f)
                {
                    //removing interpolate
                    //blending from currentRotation to transform to layer rotation

                    float deltaBlend = (boneInterpolatedRotation.degreesPerSecond * delta) / boneInterpolatedRotation.angularDistance;
                    boneInterpolatedRotation.blendAmount = (float)Unigine.MathLib.Max(boneInterpolatedRotation.blendAmount - deltaBlend, 0.0f);
                    ApplyBoneInterpolatedRotation(boneInterpolatedRotation);
                    if (boneInterpolatedRotation.blendAmount == 0.0f)
                    {
                        boneInterpolatedRotations.Remove(boneInterpolatedRotation);
                        onClearBoneInterpolateDone.Run(boneInterpolatedRotation.boneName);
                    }
                }

            }
        }

        for (int i = boneRotations.Count - 1; i >= 0; i--)
        {
            BoneRotation boneRotation = boneRotations[i];
            if (boneRotation.blendOutDegreesPerSecond == 0.0f)
            {
                ApplyBoneRotation(boneRotation.boneIndex, boneRotation.rotation);
            }
            else
            {
                UpdateRotationBlendOut(boneRotation.boneIndex);
                ApplyBoneRotation(boneRotation.boneIndex, boneRotation.rotation);
                if (boneRotation.blendOutAmount == 1.0f)
                {
                    boneRotations.Remove(boneRotation);
                    onClearBoneRotationSmoothDone.Run(meshSkinned.GetBoneName(boneRotation.boneIndex));
                }
            }
        }
    }

    private void ApplyBoneInterpolatedRotation(BoneInterpolatedRotation boneInterpolatedRotation)
    {
        //mat4 currentXform = meshSkinned.GetLayerBoneTransform(0, boneInterpolatedRotation.boneIndex);
        quat currentRotation;
        //Log.Warning("\ngetting here "+ boneInterpolatedRotation.blendAmount);
        //quat remainingQuat;
        if (boneInterpolatedRotation.blendTarget == 1.0f)
        {
            currentRotation = Unigine.MathLib.Slerp(boneInterpolatedRotation.startRotation, boneInterpolatedRotation.targetRotation, boneInterpolatedRotation.blendAmount);
            //remainingQuat = boneInterpolatedRotation.currentRotation - boneInterpolatedRotation.targetRotation;
        }
        else
        {
            currentRotation = Unigine.MathLib.Slerp(quat.IDENTITY, boneInterpolatedRotation.targetRotation, boneInterpolatedRotation.blendAmount);
            //remainingQuat = boneInterpolatedRotation.currentRotation - meshSkinned.GetLayerBoneRotation(0, boneInterpolatedRotation.boneIndex);
        }
        //remainingQuat.Get(out vec3 axis, out float angle);
        //boneInterpolatedRotation.angularDistance = angle;
        boneInterpolatedRotation.currentRotation = currentRotation;
        meshSkinned.SetLayerBoneRotation(0, boneInterpolatedRotation.boneIndex, meshSkinned.GetLayerBoneRotation(0, boneInterpolatedRotation.boneIndex) * currentRotation);
    }

    private void ApplyBoneRotation(int boneIndex, quat targetRotation)
    {
        //mat4 finalXform = meshSkinned.GetLayerBoneTransform(0, boneIndex) * new mat4(targetRotation);
        meshSkinned.SetLayerBoneRotation(0, boneIndex, meshSkinned.GetLayerBoneRotation(0, boneIndex) * targetRotation);
    }
    private BoneInterpolatedRotation FindBoneRotationInterpolate(int boneIndex)
    {
        foreach (BoneInterpolatedRotation bxform in boneInterpolatedRotations)
        {
            if (bxform.boneIndex == boneIndex)
                return bxform;
        }
        return null;
    }

    private BoneRotation FindBoneRotation(int boneIndex)
    {
        foreach (BoneRotation bxform in boneRotations)
        {
            if (bxform.boneIndex == boneIndex)
                return bxform;
        }
        return null;
    }

    public void RotateBoneTo(string boneName, quat targetRotation)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
#if DEBUG
        if (boneIndex == -1)
        {
            Log.Message($"RotateBoneTo: bone {boneName} not found\n");
            return;
        }

        var boneInterpolatedRotation = FindBoneRotationInterpolate(boneIndex);
        if (boneInterpolatedRotation != null)
        {
            Log.Message($"RotateBoneTo: bone {boneName} is being interpolated and cannot be rotated\n");
            return;
        }
#endif
        BoneRotation boneRotation = FindBoneRotation(boneIndex);
        quat startRotation = meshSkinned.GetLayerBoneRotation(0, boneIndex);
        if (boneRotation == null)
        {
            boneRotation = new BoneRotation()
            {
                boneIndex = boneIndex,
                boneName = boneName,
                rotation = MathLib.Inverse(startRotation) * targetRotation,
            };
            boneRotations.Add(boneRotation);
        }
        else
        {
            boneRotation.rotation = MathLib.Inverse(startRotation) * targetRotation;
            boneRotation.blendOutDegreesPerSecond = 0.0f;
        }
    }
    public void RotateBoneBy(string boneName, quat deltaRotation)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
#if DEBUG
        if (boneIndex == -1)
        {
            Log.Message($"RotateBoneBy: bone {boneName} not found\n");
            return;
        }

        var boneInterpolatedRotation = FindBoneRotationInterpolate(boneIndex);
        if (boneInterpolatedRotation != null)
        {
            Log.Message($"RotateBoneBy: bone {boneName} is being interpolated and cannot be rotated\n");
            return;
        }
#endif
        BoneRotation boneRotation = FindBoneRotation(boneIndex);
        if (boneRotation == null)
        {
            boneRotation = new BoneRotation()
            {
                boneIndex = boneIndex,
                rotation = deltaRotation,
                blendOutDegreesPerSecond = 0.0f,
                boneName = boneName
            };
            boneRotations.Add(boneRotation);
        }
        else
        {
            boneRotation.rotation *= deltaRotation;
            boneRotation.blendOutDegreesPerSecond = 0.0f;
        }
    }
    public void RotateBoneByInterpolated(string boneName, quat deltaQuat, float speed = 20.0f)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
#if DEBUG
        if (boneIndex == -1)
        {
            Log.Message($"RotateBoneByInterpolated: bone {boneName} not found\n");
            return;
        }
        BoneRotation boneRotation = FindBoneRotation(boneIndex);
        if (boneRotation != null)
        {
            Log.Message($"RotateBoneByInterpolated: bone {boneName} is being rotated and cannot be interpolated\n");
            return;
        }
#endif
        BoneInterpolatedRotation boneInterpolatedRotation = FindBoneRotationInterpolate(boneIndex);
        //quat startRotation;
        if (boneInterpolatedRotation == null)
        {
            boneInterpolatedRotation = new BoneInterpolatedRotation()
            {
                boneIndex = boneIndex,
                boneName = boneName,
                startRotation = quat.IDENTITY,
                targetRotation = deltaQuat
            };
            boneInterpolatedRotations.Add(boneInterpolatedRotation);
        }
        else
        {
            if (boneInterpolatedRotation.blendAmount > 0.0f && boneInterpolatedRotation.blendAmount < 1.0f)
                return;
            boneInterpolatedRotation.startRotation = boneInterpolatedRotation.currentRotation;
            boneInterpolatedRotation.targetRotation = boneInterpolatedRotation.currentRotation * deltaQuat;
        }

        boneInterpolatedRotation.blendTarget = 1.0f;
        boneInterpolatedRotation.blendAmount = 0.0f;
        boneInterpolatedRotation.degreesPerSecond = MathLib.Abs(speed);
        (deltaQuat).Get(out vec3 axis, out float angle);
        boneInterpolatedRotation.angularDistance = MathLib.Abs(angle);
    }

    public void RotateBoneToInterpolated(string boneName, quat targetQuat, float speed = 20.0f)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
#if DEBUG
        if (boneIndex == -1)
        {
            Log.Message($"RotateBoneToInterpolated: bone {boneName} not found\n");
            return;
        }
        BoneRotation boneRotation = FindBoneRotation(boneIndex);
        if (boneRotation != null)
        {
            Log.Message($"RotateBoneToInterpolated: bone {boneName} is being rotated and cannot be interpolated\n");
            return;
        }

#endif
        BoneInterpolatedRotation boneInterpolatedRotation = FindBoneRotationInterpolate(boneIndex);
        quat startRotation;
        startRotation = meshSkinned.GetLayerBoneRotation(0, boneIndex);
        if (boneInterpolatedRotation == null)
        {
            boneInterpolatedRotation = new BoneInterpolatedRotation()
            {
                boneName = boneName,
                boneIndex = boneIndex,
                startRotation = quat.IDENTITY,
                targetRotation = MathLib.Inverse(startRotation) * targetQuat
            };
            boneInterpolatedRotations.Add(boneInterpolatedRotation);
        }
        else
        {
            if (boneInterpolatedRotation.blendAmount > 0.0f && boneInterpolatedRotation.blendAmount < 1.0f)
                return;
            boneInterpolatedRotation.startRotation = boneInterpolatedRotation.currentRotation;
            boneInterpolatedRotation.targetRotation = boneInterpolatedRotation.currentRotation * MathLib.Inverse(startRotation) * targetQuat;
        }

        boneInterpolatedRotation.blendTarget = 1.0f;
        boneInterpolatedRotation.blendAmount = 0.0f;
        boneInterpolatedRotation.degreesPerSecond = MathLib.Abs(speed);
        (MathLib.Inverse(startRotation) * targetQuat).Get(out vec3 axis, out float angle);
        boneInterpolatedRotation.angularDistance = MathLib.Abs(angle);
    }

    public void SetInterpolatedBoneRotationSpeed(string boneName, float degreesPerSecond)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
        if (boneIndex == -1)
        {
            Log.Message($"ClearInterpolatedBoneRotation: bone {boneName} not found\n");
            return;
        }
        BoneInterpolatedRotation boneInterpolatedRotation = FindBoneRotationInterpolate(boneIndex);
        if (boneInterpolatedRotation != null)
        {
            boneInterpolatedRotation.degreesPerSecond = degreesPerSecond;
        }
        else
        {
            Log.Message($"ClearInterpolatedBoneRotation: no bone interpolator found for {boneName}");
        }
    }

    public void ClearInterpolatedBoneRotation(string boneName)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
        if (boneIndex == -1)
        {
            Log.Message($"ClearInterpolatedBoneRotation: bone {boneName} not found\n");
            return;
        }
        BoneInterpolatedRotation boneInterpolatedRotation = FindBoneRotationInterpolate(boneIndex);
        if (boneInterpolatedRotation != null)
        {
            boneInterpolatedRotation.blendTarget = 0.0f;
        }
        else
        {
            Log.Message($"ClearInterpolatedBoneRotation: no bone interpolator found for {boneName}");
        }
    }

    public void ClearInterpolatedBoneRotationImmediate(string boneName)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
        if (boneIndex == -1)
        {
            Log.Message($"ClearInterpolatedBoneRotationImmediate: bone {boneName} not found\n");
            return;
        }
        BoneInterpolatedRotation boneInterpolatedRotation = FindBoneRotationInterpolate(boneIndex);
        if (boneInterpolatedRotation != null)
        {
            boneInterpolatedRotations.Remove(boneInterpolatedRotation);
        }
        else
        {
            Log.Message($"ClearInterpolatedBoneRotationImmediate: no bone rotation found for {boneName}");
        }
    }

    public void ClearBoneRotation(string boneName, float speed = 20.0f)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
        if (boneIndex == -1)
        {
            Log.Message($"ClearBoneRotation: bone {boneName} not found\n");
            return;
        }
        BoneRotation boneRotation = FindBoneRotation(boneIndex);
        if (boneRotation != null)
        {
            boneRotation.blendOutDegreesPerSecond = speed;
            boneRotation.blendOutAmount = 0.0f;
        }
        else
        {
            Log.Message($"ClearBoneRotation: no bone rotation found for {boneName}");
        }
    }

    public void ClearBoneRotationImmediate(string boneName)
    {
        int boneIndex = meshSkinned.FindBone(boneName);
        if (boneIndex == -1)
        {
            Log.Message($"ClearBoneRotationImmediate: bone {boneName} not found\n");
            return;
        }
        BoneRotation boneRotation = FindBoneRotation(boneIndex);
        if (boneRotation != null)
        {
            boneRotations.Remove(boneRotation);
        }
        else
        {
            Log.Message($"ClearBoneRotationImmediate: no bone rotation found for {boneName}");
        }
    }

    private void UpdateRotationBlendOut(int boneIndex)
    {
        float deltaTime = updateTimeDelta * timeScale;
        BoneRotation boneRotation = FindBoneRotation(boneIndex);
        if (boneRotation != null)
        {
            boneRotation.rotation.Get(out vec3 axis, out float deltaAngle);
            boneRotation.blendOutAmount += (deltaTime * boneRotation.blendOutDegreesPerSecond) / (deltaAngle);
            boneRotation.blendOutAmount = MathLib.Min(boneRotation.blendOutAmount, 1.0f);
            boneRotation.rotation = Unigine.MathLib.Slerp(boneRotation.rotation, quat.IDENTITY, boneRotation.blendOutAmount);
        }
    }
    #endregion

    #region utilities

    private NamedAnimation GetNamedAnimation(string animationName)
    {
        NamedAnimation result = animations.Find(animation => animation.name == animationName);
        if (result != null)
            return result;
        Log.Warning($"\nAnimation {animationName} not found");
        return new NamedAnimation();
    }

    private void CheckTrigger(AnimationTrigger animationTrigger, int layerNum, int totalFrames, bool reversing = false)
    {
        float animationTime = meshSkinned.GetLayerFrame(layerNum) % totalFrames;

        if (animationTrigger.currentFrame == -1.0f)
        {
            animationTrigger.currentFrame = animationTime;
            return;
        }
        if (!reversing)
        {
            if (animationTime > animationTrigger.currentFrame)
            {
                if (animationTrigger.currentFrame < animationTrigger.frame && animationTrigger.frame < animationTime)
                {
                    if (animationTrigger.callback.Enabled)
                        animationTrigger.callback.Run();
                }
            }
        }
        else
        {
            if (animationTime > 0.0f)
            {
                if (animationTime < animationTrigger.currentFrame)
                {
                    if (animationTrigger.currentFrame > animationTrigger.frame && animationTrigger.frame > animationTime)
                    {
                        if (animationTrigger.callback.Enabled)
                            animationTrigger.callback.Run();
                    }
                }
            }

        }
        animationTrigger.currentFrame = animationTime;
    }
    #endregion

    #region services

    public void QueueCommand(Action<BasicAnimation> callback)
    {
        EventDelegate<BasicAnimation> command = null;
        command = (BasicAnimation) => {
            callback.Invoke(BasicAnimation);
            postAnimationUpdate.Disconnect(command);
        };
        postAnimationUpdate.Connect(command);
    }
    public void SetAnimationTimeScale(float timescale)
    {
        timeScale = timescale;
    }
    public float GetAnimationTimeScale()
    {
        return timeScale;
    }
    public void SetProcessRate(int fps)
    {
        if (fps > 0)
        {
            processRate = fps;
            processType = AnimationProcessTypes.CustomRate;
            updateTime = (float)(1.0f / processRate);
        }
        else
        {
            processType = AnimationProcessTypes.EveryFrame;
            Log.Warning($"setBlendTreeUpdate: fps must be greater than 0");
        }
    }

    public int GetProcessRate()
    {
        return processRate;
    }

    public string GetProcessType()
    {
        return (string)processType.ToString();
    }

    public void SetProcessEveryFrame()
    {
        processType = AnimationProcessTypes.EveryFrame;
        lastUpdateTime = 0.0f;
    }

    public mat4 GetBoneLocalTransform(string boneName)
    {
        int index = meshSkinned.FindBone(boneName);
        if (index == -1)
        {
            Log.Warning($"getBoneTransform: bone name {boneName} not found");
            return mat4.ZERO;
        }
        return meshSkinned.GetLayerBoneTransform(0, index);
    }
    public Mat4 GetBoneWorldTransform(string boneName)
    {
        int index = meshSkinned.FindBone(boneName);
        if (index == -1)
        {
            Log.Warning($"getBoneTransform: bone name {boneName} not found");
            return mat4.ZERO;
        }
        return meshSkinned.WorldTransform * meshSkinned.GetLayerBoneTransform(0, index);
    }
    public quat GetBoneLocalRotation(string boneName)
    {
        int index = meshSkinned.FindBone(boneName);
        if (index == -1)
        {
            Log.Warning($"getBoneTransform: bone name {boneName} not found");
            return quat.IDENTITY;
        }
        return meshSkinned.GetLayerBoneRotation(0, index);
    }
    public quat GetBoneWorldRotation(string boneName)
    {
        int index = meshSkinned.FindBone(boneName);
        if (index == -1)
        {
            Log.Warning($"getBoneTransform: bone name {boneName} not found");
            return quat.IDENTITY;
        }
        return meshSkinned.GetRotation() * meshSkinned.GetLayerBoneRotation(0, index);
    }
    #endregion
}