using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using Unigine;
using static Blend2D;

[Component(PropertyGuid = "AUTOGENERATED_GUID")]
public class Tracker : Component
{
    [ShowInEditor]
    [ParameterFile]
    private string trackerWrapperUsc = "";

    [ShowInEditor]
    [ParameterFile(Filter = ".track")]
    private List<string> trackFiles = new List<string>();

    private List<int> tracks = new List<int> { };

    private List<float> trackTimes = new List<float> { };

    private static bool isWrapperLoaded = false;

    private static readonly Variable initFunc = new Variable("TrackerWrapper::init");
    private static readonly Variable shutdownFunc = new Variable("TrackerWrapper::shutdown");
    private static readonly Variable addTrackFunc = new Variable("TrackerWrapper::addTrack");
    private static readonly Variable removeTrackFunc = new Variable("TrackerWrapper::removeTrack");
    private static readonly Variable getMinTimeFunc = new Variable("TrackerWrapper::getMinTime");
    private static readonly Variable getMaxTimeFunc = new Variable("TrackerWrapper::getMaxTime");
    private static readonly Variable getUnitTimeFunc = new Variable("TrackerWrapper::getUnitTime");
    private static readonly Variable setFunc = new Variable("TrackerWrapper::set");

    private static Dictionary<string, int> trackIDs = new Dictionary<string, int>();
    private static Dictionary<int, bool> activeTracks = new Dictionary<int, bool>();

    private static Variable trackFileVar = new Variable("");
    private static Variable trackIdVar = new Variable(0);
    private static Variable timeVar = new Variable(0.0f);

    public static bool IsInitialized { get; private set; } = false;

    private EventInvoker<string> onTrackDone = new EventInvoker<string>();

    private class TrackerTrigger
    {
        public string name;
        public string trackName;
        public float currentTime = -1;
        public float targetTime;
        public EventInvoker callback = new EventInvoker();
        
    };

    private static List<TrackerTrigger> trackerTriggers = new List<TrackerTrigger>();

    public static int AddTrack(string trackFile)
    {
        if (IsInitialized && FileSystem.IsFileExist(trackFile) && FileSystem.GetExtension(trackFile) == "track")
        {
            string trackName = trackFile.Split('.')[0];
            string[] parts = trackName.Split('/');
            trackName = parts[parts.Length - 1];

            if (!trackIDs.ContainsKey(trackName))
            {
                trackFileVar.String = trackFile;
                int trackID = Engine.RunWorldFunction(addTrackFunc, trackFileVar).Int;
                trackIDs[trackName] = trackID;

                return trackID;
            }
            else
            {
                Log.Warning($"Tracker::AddTrack: {trackFile} already added\n");
                return trackIDs[trackName];
            }
        }

        return -1;
    }

    public static Boolean RemoveTrack(int trackID)
    {
        if (IsInitialized && trackIDs.ContainsValue(trackID))
        {
            trackIdVar.Int = trackID;
            Engine.RunWorldFunction(removeTrackFunc, trackIdVar);

            foreach (var pair in trackIDs)
            {
                if (pair.Value.Equals(trackID))
                {
                    trackIDs.Remove(pair.Key);
                    return true;
                }
            }
        }
        return false;
    }

    public static void RemoveTrack(string trackName)
    {
        if (IsInitialized && trackIDs.ContainsKey(trackName))
        {
            if(!RemoveTrack(trackIDs[trackName]))
                Log.Warning($"Tracker::RemoveTrack: {trackName} not found\n");
        }
            
    }

    public static void PlayTrack(string trackName, bool loop = false)
    {
        if (IsInitialized && trackIDs.ContainsKey(trackName))
        {
            if(!activeTracks.ContainsKey(GetTrackID(trackName)))
                activeTracks.Add(GetTrackID(trackName), loop);
        }            
    }

    public static void PauseTrack(string trackName)
    {
        if (IsInitialized && trackIDs.ContainsKey(trackName))
            activeTracks.Remove(GetTrackID(trackName));
    }

    public void AddAnimationDoneCB(EventDelegate<string> cb)
    {
        onTrackDone.Connect(cb);
    }

    public void RemoveAnimationCB(EventDelegate<string> cb)
    {
        onTrackDone.Disconnect(cb);
    }

    public static bool ContainsTrack(string trackName)
    {
        if (IsInitialized)
            return trackIDs.ContainsKey(trackName);

        return false;
    }

    public static int GetTrackID(string trackName)
    {
        if (IsInitialized && trackIDs.ContainsKey(trackName))
            return trackIDs[trackName];

        return -1;
    }

    public static string GetTrackName(int Id)
    {
        if (IsInitialized)
        {
            if (trackIDs.ContainsValue(Id)){
                foreach(var key in trackIDs.Keys)
                {
                    if (trackIDs[key] == Id)
                        return key;
                }
            }
        }
        return String.Empty;
    }

    public static float GetMinTime(int trackID)
    {
        if (IsInitialized)
        {
            trackIdVar.Int = trackID;
            return Engine.RunWorldFunction(getMinTimeFunc, trackIdVar).Float;
        }

        return 0.0f;
    }

    public static float GetMinTime(string trackName)
    {
        if (IsInitialized && trackIDs.ContainsKey(trackName))
            return GetMinTime(trackIDs[trackName]);

        return 0.0f;
    }

    public static float GetMaxTime(int trackID)
    {
        if (IsInitialized)
        {
            trackIdVar.Int = trackID;
            return Engine.RunWorldFunction(getMaxTimeFunc, trackIdVar).Float;
        }

        return 0.0f;
    }

    public static float GetMaxTime(string trackName)
    {
        if (IsInitialized && trackIDs.ContainsKey(trackName))
            return GetMaxTime(trackIDs[trackName]);

        return 0.0f;
    }

    public static float GetUnitTime(int trackID)
    {
        if (IsInitialized)
        {
            trackIdVar.Int = trackID;
            return Engine.RunWorldFunction(getUnitTimeFunc, trackIdVar).Float;
        }

        return 0.0f;
    }

    public static float GetUnitTime(string trackName)
    {
        if (IsInitialized && trackIDs.ContainsKey(trackName))
            return GetUnitTime(trackIDs[trackName]);

        return 0.0f;
    }

    public static void SetTime(int trackID, float time)
    {
        if (IsInitialized)
        {
            timeVar.Float = time;
            trackIdVar.Int = trackID;
            Engine.RunWorldFunction(setFunc, trackIdVar, timeVar);
        }
    }

    public static void SetTime(string trackName, float time)
    {
        if (IsInitialized && trackIDs.ContainsKey(trackName))
            SetTime(trackIDs[trackName], time);
    }

    public static void ListTracks()
    {
        foreach (var pair in trackIDs)
        {
            string message = pair.Key+": "+pair.Value;
        }
    }

    public static void AddTrackerTrigger(string name, string trackName, float time, EventDelegate cb)
    {
        TrackerTrigger animationTrigger = new TrackerTrigger() { name = name, targetTime = time, trackName = trackName, currentTime = -1.0f };
        animationTrigger.callback.Connect(cb);
        trackerTriggers.Add(animationTrigger);
    }

    public static void RemoveTrackerTrigger(string name, EventDelegate cb)
    {
        //foreach (AnimationTrigger animationTrigger in fbAnimationTriggers)
        for (int i = trackerTriggers.Count - 1; i >= 0; i--)
        {
            TrackerTrigger trackerTrigger = trackerTriggers[i];
            if (trackerTrigger.name == name)
            {
                trackerTrigger.callback.Disconnect(cb);
                trackerTriggers.Remove(trackerTrigger);
                break;
            }
        }
    }

    private void checkTrigger(int trackId, float time)
    {
        string trackName = GetTrackName(trackId);
        if (trackName == String.Empty)
            return;

        TrackerTrigger trackerTrigger = null;
        foreach (TrackerTrigger trigger in trackerTriggers)
        {
            if (trigger.trackName == trackName)
            {
                trackerTrigger = trigger;
                break;
            }
        }
        if (trackerTrigger == null)
            return;
        
        if (trackerTrigger.currentTime == -1.0f)
        {
            trackerTrigger.currentTime = time;
            return;
        }
        if (time > trackerTrigger.currentTime)
        {
            if (trackerTrigger.currentTime < trackerTrigger.targetTime && trackerTrigger.targetTime < time)
            {
                trackerTrigger.callback.Run();
            }
        }
        trackerTrigger.currentTime = time;
    }

    // initialize tracker before all components
    [MethodInit(Order = int.MinValue)]
    private void Init()
    {
        // check tracker wrapper
        string trackerWrapperGUID = FileSystem.GuidToPath(FileSystem.GetGUID(trackerWrapperUsc));
        isWrapperLoaded = (World.ScriptName == trackerWrapperGUID);

        // add tracker_wrapper to world logic if not set in editor
        if (!isWrapperLoaded)
        {
            Log.WarningLine($"{trackerWrapperUsc} not setup as world script. Setup it in Editor.");
            return;
        }

        // init tracker in wrapper
        Engine.RunWorldFunction(initFunc);
        IsInitialized = true;

        // add tracks
        if (trackFiles != null)
        {
            foreach (var track in trackFiles)
            {
                //Log.Message("Adding track:");
                int trackID = AddTrack(track);
                //Log.Message($"{track}\n");
                if (trackID != -1)
                {
                    tracks.Add(trackID);
                    trackTimes.Add(GetMinTime(trackID));
                }
            }
        }
        ListTracks();
        //AddAnimationDoneCB(OnTrackFinished);
        //AddTrackerTrigger("triggertest", "test2", 2.5f, TrackerTriggerTest);
    }

    public void TrackerTriggerTest()
    {
        Log.Message("\ntest trigger");
    }

    public void OnTrackFinished(string trackName)
    {
        Log.Message($"\nOn {trackName} finished");
    }

    public void Disable()
    {
        node.Enabled = false;
    }

    public void Enable()
    {
        node.Enabled = true;
    }

    private void Update()
    {

        if (Input.IsKeyDown(Input.KEY.P))
        {
            PlayTrack("test", true);
            PlayTrack("test2", true);
        }

        if (Input.IsKeyDown(Input.KEY.O))
        {
            PauseTrack("test");
            PauseTrack("test2");
        }
        if (activeTracks.Count > 0)
        {
            int i = 0;
            foreach (int trackID in tracks)
            {
                if (activeTracks.Keys.Contains(trackID))
                {
                    float minTime = GetMinTime(trackID);
                    float maxTime = GetMaxTime(trackID);
                    float unitTime = GetUnitTime(trackID);

                    trackTimes[i] += Game.IFps / unitTime;
                    if (trackTimes[i] >= maxTime)
                    {
                        if (!activeTracks[trackID])//boolean value at activeTracks key determines whether to loop
                        {
                            activeTracks.Remove(trackID);
                        }
                            
                        trackTimes[i] = minTime;
                        onTrackDone.Run(GetTrackName(trackID));
                        //Log.Message($"{GetTrackName(trackID)} animation done.");
                    }
                    SetTime(trackID, trackTimes[i]);
                    if(trackerTriggers.Count > 0) { }
                        checkTrigger(trackID, trackTimes[i]);

                }
                i++;
            }
        }


    }

    // shutdown tracker after all components
    [MethodShutdown(Order = int.MaxValue)]
    private void Shutdown()
    {
        if (IsInitialized)
        {
            // shutdown tracker in wrapper
            Engine.RunWorldFunction(shutdownFunc);

            trackIDs.Clear();
            activeTracks.Clear();
            isWrapperLoaded = false;
            IsInitialized = false;
        }
    }
}
